package server
import "net/http"
func(s *Server)dashboard(w http.ResponseWriter,r *http.Request){w.Header().Set("Content-Type","text/html; charset=utf-8");w.Write([]byte(dashHTML))}
const dashHTML=`<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Signalman</title>
<style>:root{--bg:#1a1410;--bg2:#241e18;--bg3:#2e261e;--rust:#c45d2c;--rl:#e8753a;--leather:#a0845c;--cream:#f0e6d3;--cd:#bfb5a3;--cm:#7a7060;--gold:#d4a843;--green:#4a9e5c;--mono:'JetBrains Mono',Consolas,monospace;--serif:'Libre Baskerville',Georgia,serif}*{margin:0;padding:0;box-sizing:border-box}body{background:var(--bg);color:var(--cream);font-family:var(--mono);font-size:13px;line-height:1.6}.hdr{padding:.6rem 1.2rem;border-bottom:1px solid var(--bg3);display:flex;justify-content:space-between;align-items:center}.hdr h1{font-family:var(--serif);font-size:1rem}.hdr h1 span{color:var(--rl)}.main{max-width:700px;margin:0 auto;padding:1rem}.btn{font-family:var(--mono);font-size:.68rem;padding:.3rem .6rem;border:1px solid;cursor:pointer;background:transparent}.btn-p{border-color:var(--rust);color:var(--rl)}.btn-p:hover{background:var(--rust);color:var(--cream)}.item{background:var(--bg2);border:1px solid var(--bg3);padding:.6rem;margin-bottom:.3rem}.item h3{font-size:.82rem;margin-bottom:.15rem}.item-meta{font-size:.65rem;color:var(--cm);display:flex;gap:.5rem;flex-wrap:wrap}.empty{text-align:center;padding:2rem;color:var(--cm);font-style:italic;font-family:var(--serif)}.modal-bg{position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,.65);display:flex;align-items:center;justify-content:center;z-index:100}.modal{background:var(--bg2);border:1px solid var(--bg3);padding:1.5rem;width:90%;max-width:500px;max-height:90vh;overflow-y:auto}.modal h2{font-family:var(--serif);font-size:.9rem;margin-bottom:1rem}label.fl{display:block;font-size:.65rem;color:var(--leather);text-transform:uppercase;letter-spacing:1px;margin-bottom:.2rem;margin-top:.5rem}input[type=text],input[type=number]{background:var(--bg);border:1px solid var(--bg3);color:var(--cream);padding:.35rem .5rem;font-family:var(--mono);font-size:.78rem;width:100%;outline:none}.del{color:var(--cm);cursor:pointer;font-size:.65rem;float:right}.del:hover{color:var(--rust)}</style></head>
<body><div class="hdr"><h1><span>Stockyard</span> Signalman</h1><button class="btn btn-p" onclick="showModal()">+ New</button></div>
<div class="main" id="list"></div>
<div class="modal-bg" id="modal" style="display:none" onclick="if(event.target===this)hideModal()"><div class="modal"><h2>New AlertRule</h2>
<label class="fl">Name</label><input type="text" id="f-name" placeholder="Name"><label class="fl">Condition</label><input type="text" id="f-condition" placeholder="Condition"><label class="fl">Threshold</label><input type="number" id="f-threshold" placeholder="Threshold"><label class="fl">Channel</label><input type="text" id="f-channel" placeholder="Channel"><label class="fl">Target</label><input type="text" id="f-target" placeholder="Target"><label class="fl">Enabled</label><input type="number" id="f-enabled" placeholder="Enabled"><label class="fl">Fire Count</label><input type="number" id="f-fire_count" placeholder="Fire Count"><label class="fl">Last Fired At</label><input type="text" id="f-last_fired_at" placeholder="Last Fired At"><label class="fl">Cooldown</label><input type="number" id="f-cooldown" placeholder="Cooldown">
<div style="margin-top:1rem;display:flex;gap:.5rem"><button class="btn btn-p" onclick="save()">Save</button><button class="btn" style="color:var(--cm);border-color:var(--bg3)" onclick="hideModal()">Cancel</button></div></div></div>
<script>
const API="/api/alert_rules";
function showModal(){document.getElementById("modal").style.display="flex"}
function hideModal(){document.getElementById("modal").style.display="none"}
async function load(){const r=await fetch(API);const d=await r.json();const el=document.getElementById("list");if(!d.alert_rules||!d.alert_rules.length){el.innerHTML='<div class="empty">No alert_rules yet</div>';return}
el.innerHTML=d.alert_rules.map(e=>'<div class="item"><span class="del" onclick="del(\'{}'.replace('{}',e.id)+'\')">[x]</span><h3>${e.name}</h3><div class="item-meta"><span>${e.condition||"—"}</span><span>${e.threshold||"—"}</span><span>${e.channel||"—"}</span><span>${e.target||"—"}</span></div></div>').join("")}
async function save(){const body={"name":document.getElementById("f-name").value,"condition":document.getElementById("f-condition").value,"threshold":parseInt(document.getElementById("f-threshold").value)||0,"channel":document.getElementById("f-channel").value,"target":document.getElementById("f-target").value,"enabled":parseInt(document.getElementById("f-enabled").value)||0,"fire_count":parseInt(document.getElementById("f-fire_count").value)||0,"last_fired_at":document.getElementById("f-last_fired_at").value,"cooldown":parseInt(document.getElementById("f-cooldown").value)||0};await fetch(API,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});hideModal();load()}
async function del(id){await fetch(API+"/"+id,{method:"DELETE"});load()}
load()
</script></body></html>` 